name: Build, Test and Tag

on: [push, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Build Node ${{ matrix.node }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        id: npm-cache
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org/'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}-${{ matrix.node }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm run test
  tag:
    runs-on: ubuntu-latest
    needs: ['setup']
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.ref, '/main') || contains(github.event.ref, '/master') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get next version
        id: get_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          pre_release_branches: 'feat*,fix*'
          append_to_pre_release_tag: 'alpha'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - name: 'Commit version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: '${{ steps.get_version.outputs.new_tag }}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto commit version bump
          tagging_message: ${{ steps.get_version.outputs.new_tag }}
