name: Build And Tag

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Build Node ${{ matrix.node }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        id: npm-cache
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org/'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}-${{ matrix.node }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm run test
  tag:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ contains(github.ref, '/main') || contains(github.ref, '/master') || contains(github.ref, '/feat') }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v1'
        with:
          node-version: 14
      - if: ${{ contains(github.ref, '/feat') }}
        name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        with:
          tag-prefix:  'v'
          default: prerelease
          preid: 'alpha'
          patch-wording: 'patch,fix'
      - if: ${{ contains(github.ref, '/main') || contains(github.ref, '/master') }}
        name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        with:
          tag-prefix:  'v'
      