name: Build And Test

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Build Node ${{ matrix.node }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        id: npm-cache
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org/'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}-${{ matrix.node }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm run test
  tag:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ contains(github.ref, '/main') || contains(github.ref, '/master') || contains(github.ref, '/feat') }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        id: npm-cache
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org/'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}-12
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - run: npm run test