name: Publish package on NPM
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        description: NPM token
        required: true

jobs:
  prepareWorkflow:
    name: Prepare workflow
    runs-on: ubuntu-latest
    outputs:
      release-type: ${{ steps.repo-meta.outputs.release-type }}
      tag-name: ${{ steps.repo-meta.outputs.tag-name }}
    steps:
      - name: Populate metadata
        id: repo-meta
        uses: globalid/github-actions/get-event-information@main
  publish:
    if: ${{ needs.prepareWorkflow.outputs.release-type }}
    needs: prepareWorkflow
    name: Build and release package
    runs-on: ubuntu-latest
    environment: ${{ needs.prepareWorkflow.outputs.release-type }}
    steps:
      - uses: globalid/github-actions/npm-setup@main
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: globalid/github-actions/npm-publish@main
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE_VERSION: ${{ needs.prepareWorkflow.outputs.tag-name }}
          RELEASE_TYPE: ${{ needs.prepareWorkflow.outputs.release-type }}