name: Create a tag

on:
  workflow_dispatch:
    workflows: ["Build And Test"]
jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          pre_release_branches: 'feat*,fix*'
          github_token: ${{ secrets.GITHUB_TOKEN }}