name: Tag push

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    needs: setup
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        id: npm-cache
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}-16
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - run: npm run test