name: Release JS SDK
on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    uses: asvetin/dummy-test-nodejs-sdk/.github/workflows/npm-publish.yml@fix-sdk
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}