name: Default SDK

on: 
  push:
    branches: 
      - '**'
    tags-ignore:
      - '*.*'
  workflow_dispatch:

jobs:
  test:
    name: Setup and test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/globalid/container-images/node-16-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    steps:
      - uses: globalid/github-actions/npm-setup@main
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run test
  